server:
  port: 9020
  servlet:
    context-path: /
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

REST_BASE_URL: http://localhost:9010
REST_INDEX_AD_URL: /content/list/89
SEARCH_BASE_URL: http://localhost:8083/search/query
ITME_INFO_URL: /item/info/
ITEM_DESC_URL: /item/desc/
ITEM_PARAM_URL: /item/param/
SSO_BASE_URL: http://localhost:8084
SSO_USER_TOKEN: /user/token/
SSO_PAGE_LOGIN: /page/login
ITEM_INFOURL: /item/info/
ORDER_BASE_URL: http://localhost:9010/order
ORDER_CREATE_URL: /create
